### ISSUE TITLE
Я выполнила задание

### ISSUE THREAD

**Issue by lunatorn** [MIEE-ACS/domashnee-zadanie-no4-lunatorn#1]
Мой вариант №2

Проверьте, пожалуйста.

**Comment by d-makarenko** [comment]
Все хорошо.

Один вопрос

            if (prFlag)
                Console.WriteLine("Произведение элементов между максимальным по модулю и минимальным по модулю: {0:N3}", pr);
            else
            {
                Console.WriteLine("Произведение элементов между максимальным по модулю и минимальным по модулю не было сформированно!");
                Console.WriteLine("Возможно таких элементов нет!");
            }

В каком случае произведение может быть не сформировано?

**Comment by lunatorn** [comment]
for (int i = 0; i<n;i++)
            {
                if ((i>imin && i<imax) || (i>imax && i<imin))
                {
                    pr *= arr[i];
                    prFlag = true;
                }
            }
В случае, если у нас не будет элементов в массиве, которые лежат между максимальным по модулю и минимальным по модулю или между минимальным по модулю и максимальным по модулю в зависимости от порядка следования максимального и минимального в массиве(imax и imin обозначают номера максимального и минимального элементов соответственно). Если элементы не лежат между imax и imin, то prFlag не установится в true, что означает что мы ни разу не изменили значение pr и оно осталось равно 1. Поэтому при выводе пишем, что произведение не было сформировано.

**Comment by d-makarenko** [comment]
Ага, точно
